### PR TITLE
feat(widget): new widget ui

### PR DESCRIPTION
**Pull request by odeinjul**
Almost finish~ed~.
Exams

Refs https://github.com/Life-USTC/Life-USTC/issues/78.

### CODE REVIEW

**Comment by tiankaima** [comment]
Merging main to fix update problems.

**Comment by odeinjul** [comment]
> Merging main to fix update problems.

I thought this is only for UI issues, and it should be merged to main rather than merge main to this branch.
~~Anyway, it doesn't matter.~~

**Comment by tiankaima** [comment]
> > Merging main to fix update problems.
> 
> I thought this is only for UI issues, and it should be merged to main rather than merge main to this branch. ~Anyway, it doesn't matter.~

You do realize that before merge, this barely even works and would never refresh throughout the day... renders that pointless and hard to daily drive..

Also the fact that Xcode Cloud would build two branch with same version number on Testflight, and one would have `build208` widget refreshing correctly, and `build209` NOT refreshing at all... kinda confusing

**Comment by odeinjul** [comment]
😢

**Pull request merged**
