### PR TITLE
feat(ui): add ui and controller to show notification in homeview

### LINKED ISSUE #37: Add UI and controller to show notification in HomeView

### PR DESCRIPTION
**Pull request by tiankaima**
## What changed

Added in-app notification support:

- Added the notification model and app lifecycle refresh.
- Added a HomeView entry and a dedicated notification list and detail surface.
- Preserved the existing async loading and error presentation patterns.

## Result

Users can open recent notifications directly from HomeView and see their content in the app.

Refs https://github.com/Life-USTC/Life-USTC/issues/77.

### CODE REVIEW

**Comment by tiankaima** [comment]
image

This looks... stupid? I guess.

**Comment by odeinjul** [comment]
What does that dot at the bottom do?

**Comment by odeinjul** [comment]
Before: 
截屏2023-07-13 12 33 11

After:
截屏2023-07-13 12 35 48

**Review by odeinjul — APPROVED** [review]
Approved.

**Comment by tiankaima** [comment]
Try squashing next time though

**Pull request merged**
